{
 "title": "Solar Status (to Share)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Produced",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(envoy_production_watthours[$__range])/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(envoy_consumption_watthours[$__range])/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(envoy_consumption_grid_watthours[$__range])/1000",
     "legendFormat": "Grid Consumed"
    },
    {
     "expr": "increase(envoy_production_watthours[$__range])/1000",
     "legendFormat": "Produced"
    },
    {
     "expr": "increase(envoy_consumption_watthours[$__range])/1000\n",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "PTO Totals",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_consumption_grid_watthours/1000",
     "legendFormat": "Grid Consumed"
    },
    {
     "expr": "envoy_production_total_watthours/1000",
     "legendFormat": "Produced"
    },
    {
     "expr": "envoy_consumption_watthours/1000\n",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Import/Export",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "format": "kwatt",
   "targets": [
    {
     "expr": "(envoy_production_watts-envoy_consumption_watts)/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produced 24h",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(envoy_production_watthours[24h])/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed 24h",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(envoy_consumption_watthours[24h]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(envoy_production_watthours[$__range])/1000",
     "legendFormat": "Production"
    },
    {
     "expr": "increase(envoy_consumption_watthours[$__range])/1000",
     "legendFormat": "Consumption"
    }
   ]
  },
  {
   "title": "PTO BANK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(envoy_production_total_watthours - envoy_consumption_watthours)/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 8 },
   "options": {
    "content": "### \\# of Panels and Type of Inverter\n### XX&deg; Pitch\n### XXX&deg; Azimuth (SSE)"
   }
  },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "envoy_consumption_watts{instance=\"enphase-exporter:2112\"}/1000",
     "legendFormat": "Home Usage"
    },
    { "expr": "envoy_production_watts/1000", "legendFormat": "Solar Power" },
    {
     "expr": "envoy_consumption_grid_watts/1000",
     "legendFormat": "Grid Usage"
    },
    { "expr": "openweather_cloudiness", "legendFormat": "clouds" },
    {
     "expr": "openweather_temperature{location=\"Flemington, NJ\"}",
     "legendFormat": "temperature"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "envoy_production_watts/1000", "legendFormat": "Production" },
    {
     "expr": "envoy_consumption_grid_watts/1000",
     "legendFormat": "Grid Consumption"
    },
    { "expr": "envoy_consumption_watts/1000", "legendFormat": "Consumption" }
   ]
  },
  { "title": "Weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Temperature, Humidity, Clouds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "openweather_feelslike", "legendFormat": "feels like" },
    { "expr": "openweather_temperature", "legendFormat": "temperature" },
    { "expr": "openweather_humidity", "legendFormat": "humidity" },
    { "expr": "openweather_cloudiness", "legendFormat": "clouds" }
   ]
  },
  {
   "title": "Rain,Snow,Wind",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "openweather_snow1h", "legendFormat": "snow" },
    { "expr": "openweather_rain1h", "legendFormat": "rain" },
    { "expr": "openweather_windspeed", "legendFormat": "wind" },
    { "expr": "openweather_pressure", "legendFormat": "pressure" }
   ]
  },
  { "title": "Monthly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } }
 ]
}